//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MastercardHost.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MastercardHost.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bind 的本地化字符串。
        /// </summary>
        internal static string BindClient {
            get {
                return ResourceManager.GetString("BindClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAPK 的本地化字符串。
        /// </summary>
        internal static string CAPK {
            get {
                return ResourceManager.GetString("CAPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string ClearScreen {
            get {
                return ResourceManager.GetString("ClearScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        internal static string ClientIP {
            get {
                return ResourceManager.GetString("ClientIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string ClientPort {
            get {
                return ResourceManager.GetString("ClientPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Client_Setting 的本地化字符串。
        /// </summary>
        internal static string ClientSetting {
            get {
                return ResourceManager.GetString("ClientSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseClient {
            get {
                return ResourceManager.GetString("CloseClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseLog {
            get {
                return ResourceManager.GetString("CloseLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseServerListen {
            get {
                return ResourceManager.GetString("CloseServerListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config 的本地化字符串。
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IssuerAuthData 的本地化字符串。
        /// </summary>
        internal static string IssuerAuthData {
            get {
                return ResourceManager.GetString("IssuerAuthData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string LogInFile {
            get {
                return ResourceManager.GetString("LogInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text 的本地化字符串。
        /// </summary>
        internal static string LogInText {
            get {
                return ResourceManager.GetString("LogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Location 的本地化字符串。
        /// </summary>
        internal static string LogLocation {
            get {
                return ResourceManager.GetString("LogLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Row Limit 的本地化字符串。
        /// </summary>
        internal static string LogRowLimit {
            get {
                return ResourceManager.GetString("LogRowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Switch 的本地化字符串。
        /// </summary>
        internal static string LogSwitch {
            get {
                return ResourceManager.GetString("LogSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Menu 的本地化字符串。
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string OpenLog {
            get {
                return ResourceManager.GetString("OpenLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Listen 的本地化字符串。
        /// </summary>
        internal static string OpenServerListen {
            get {
                return ResourceManager.GetString("OpenServerListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RespCode 的本地化字符串。
        /// </summary>
        internal static string RespCode {
            get {
                return ResourceManager.GetString("RespCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Revokey 的本地化字符串。
        /// </summary>
        internal static string Revokey {
            get {
                return ResourceManager.GetString("Revokey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script 的本地化字符串。
        /// </summary>
        internal static string Script {
            get {
                return ResourceManager.GetString("Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self Define 的本地化字符串。
        /// </summary>
        internal static string SelfDefine {
            get {
                return ResourceManager.GetString("SelfDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP 的本地化字符串。
        /// </summary>
        internal static string ServerIP {
            get {
                return ResourceManager.GetString("ServerIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Port 的本地化字符串。
        /// </summary>
        internal static string ServerPort {
            get {
                return ResourceManager.GetString("ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Server_Setting 的本地化字符串。
        /// </summary>
        internal static string ServerSetting {
            get {
                return ResourceManager.GetString("ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MasterCard Auto Test Tool 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Input Only Number 的本地化字符串。
        /// </summary>
        internal static string TitleDialog {
            get {
                return ResourceManager.GetString("TitleDialog", resourceCulture);
            }
        }
    }
}
